/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package distsys.smarttutor.gui;

import generated.grpc.smarttutor.DoubtsServiceGrpc;
import generated.grpc.smarttutor.RequestQuestion;
import generated.grpc.smarttutor.SmartAnswer;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;

import javax.swing.JOptionPane;


/**
 *
 * @author bruol
 */
public class DoubsFrame extends javax.swing.JFrame {
    
    private DoubtsServiceGrpc.DoubtsServiceBlockingStub doubtsBlockingStub;
    private ManagedChannel channel;
    
    /**
     * Creates new form DoubsFrame
     */
    public DoubsFrame() {
        initComponents();
        setupGrpcConnection();
    }
    
    private void setupGrpcConnection() {
        // Configurar o canal gRPC (substitua "localhost" e 50051 pelos seus dados)
        channel = ManagedChannelBuilder.forAddress("localhost", 50051)
                .usePlaintext()
                .build();
        doubtsBlockingStub = DoubtsServiceGrpc.newBlockingStub(channel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jColorChooser3 = new javax.swing.JColorChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        studentQuestion = new javax.swing.JTextField();
        sendQuestion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        answerField = new javax.swing.JTextArea();
        exitQuestion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Doubts Section");
        setBackground(new java.awt.Color(212, 148, 157));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel1.setText("Enter your question for the Smart Tutor:");

        jLabel2.setText("Question:");

        jLabel3.setText("Smart Tutor Answer:");

        studentQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentQuestionActionPerformed(evt);
            }
        });

        sendQuestion.setText("Send");
        sendQuestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendQuestionActionPerformed(evt);
            }
        });

        answerField.setColumns(20);
        answerField.setRows(5);
        jScrollPane1.setViewportView(answerField);

        exitQuestion.setText("Exit");
        exitQuestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitQuestionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studentQuestion)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendQuestion)
                    .addComponent(exitQuestion))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(studentQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sendQuestion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitQuestion))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentQuestionActionPerformed

    private void exitQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitQuestionActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitQuestionActionPerformed

    private void sendQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendQuestionActionPerformed
        if(studentQuestion.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Please enter your question");
        } else{
            String question = studentQuestion.getText().trim();
            
            RequestQuestion request = RequestQuestion.newBuilder()
                    .setQuestion(question)
                    .build();
            try {
                
                SmartAnswer response = doubtsBlockingStub.studentQuestion(request);
                
                answerField.setText(response.getAnswer());
            } catch (Exception ex) {
                answerField.setText("Erro ao enviar a pergunta: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_sendQuestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoubsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoubsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoubsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoubsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoubsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea answerField;
    private javax.swing.JButton exitQuestion;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JColorChooser jColorChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sendQuestion;
    private javax.swing.JTextField studentQuestion;
    // End of variables declaration//GEN-END:variables
}
