/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package distsys.smarttutor.gui;

import generated.grpc.smarttutor.GradeEssayServiceGrpc;
import generated.grpc.smarttutor.GradeEssayServiceGrpc.GradeEssayServiceStub;
import generated.grpc.smarttutor.Essay;
import generated.grpc.smarttutor.EssayGraded;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.stub.StreamObserver;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author bruol
 */
public class GradeEssayFrame extends javax.swing.JFrame {

    private ManagedChannel channel;
    private GradeEssayServiceStub stub;

    /**
     * Creates new form GradeEssayFrame
     */
    public GradeEssayFrame() {
        initComponents();

        channel = ManagedChannelBuilder.forAddress("localhost", 50051)
                .usePlaintext()
                .build();
        stub = GradeEssayServiceGrpc.newStub(channel);
        
        essaySend.addActionListener((ActionEvent evt) -> sendEssayToServer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        essaySend = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        essayFeedback = new javax.swing.JTextField();
        ExitEssay = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        essayToStream = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Essay");
        setBackground(new java.awt.Color(212, 148, 157));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel1.setText("Essay Grading ");

        jLabel2.setText("Please submit your essay bellow:");

        essaySend.setText("Send");
        essaySend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        essaySend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                essaySendActionPerformed(evt);
            }
        });

        jLabel3.setText("Here are a few things about your essay:");

        ExitEssay.setText("Exit");
        ExitEssay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitEssayActionPerformed(evt);
            }
        });

        essayToStream.setColumns(20);
        essayToStream.setRows(5);
        jScrollPane1.setViewportView(essayToStream);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(essaySend)
                            .addComponent(ExitEssay)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(essayFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel1)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(essaySend)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(essayFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(ExitEssay)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitEssayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitEssayActionPerformed
        this.dispose();
    }//GEN-LAST:event_ExitEssayActionPerformed

    private void essaySendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_essaySendActionPerformed
      
    }//GEN-LAST:event_essaySendActionPerformed

    private void sendEssayToServer() {
    essayFeedback.setText("Sending...");
    String fullText = essayToStream.getText().trim();
    if (fullText.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter your essay");
        return;
    } 
    
    StreamObserver<EssayGraded> responseObserver = new StreamObserver<EssayGraded>() {
    @Override
    public void onNext(EssayGraded value) {
    essayFeedback.setText(value.getFeedback());
    }
    
    @Override
    public void onError(Throwable t) {
    JOptionPane.showMessageDialog(null, "Error: " + t.getMessage());
    }
    
    @Override
    public void onCompleted() {
    JOptionPane.showMessageDialog(null, "Essay submitted and graded.");
    }
    };
    
    StreamObserver<Essay> requestObserver = stub.studentEssay(responseObserver);
    String[] paragraphs = fullText.split("\n\n");
    for (String para : paragraphs) {
    if (!para.trim().isEmpty()) {
    Essay essay = Essay.newBuilder().setPartEssay(para.trim()).build();
    requestObserver.onNext(essay);
    }
    }
    requestObserver.onCompleted();
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradeEssayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradeEssayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradeEssayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradeEssayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradeEssayFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitEssay;
    private javax.swing.JTextField essayFeedback;
    private javax.swing.JButton essaySend;
    private javax.swing.JTextArea essayToStream;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
