/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package distsys.smarttutor.gui;

import distsys.smarttutor.Server.ReviewContentServiceImpl;
import generated.grpc.smarttutor.ReviewContentServiceGrpc;
import generated.grpc.smarttutor.ReviewContentServiceGrpc.ReviewContentServiceStub;
import generated.grpc.smarttutor.RequestContent;
import generated.grpc.smarttutor.ContentReply;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;


/**
 *
 * @author bruol
 */
public class ReviewContentFrame extends javax.swing.JFrame {
    
    private ManagedChannel channel;
    private ReviewContentServiceStub stub;
    /**
     * Creates new form ReviewContentFrame
     */
    public ReviewContentFrame() {
        initComponents();
        
              
        contentOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "Math", "Science", "Reading and Language", "Social Studies"
        }));
        
        channel = ManagedChannelBuilder.forAddress("localhost", 50051)
                .usePlaintext()
                .build();
        stub = ReviewContentServiceGrpc.newStub(channel);
        
        sendReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendReviewActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        contentOption = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        exitReview = new javax.swing.JButton();
        sendReview = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        reviewResults = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Review");
        setBackground(new java.awt.Color(212, 148, 157));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel1.setText("Review Time!");

        jLabel2.setText("Which Content you would like to Study?");

        contentOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        contentOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentOptionActionPerformed(evt);
            }
        });

        jLabel3.setText("Tips to start studying:");

        exitReview.setText("Exit");
        exitReview.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitReviewActionPerformed(evt);
            }
        });

        sendReview.setText("Send");
        sendReview.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendReviewActionPerformed(evt);
            }
        });

        reviewResults.setColumns(20);
        reviewResults.setRows(5);
        jScrollPane2.setViewportView(reviewResults);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(contentOption, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitReview)
                            .addComponent(sendReview))))
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(contentOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sendReview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitReview)))
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitReviewActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitReviewActionPerformed

    private void contentOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentOptionActionPerformed
        String selectedContent = (String) contentOption.getSelectedItem();
        
        reviewResults.setText("Please send your review request using the 'Send' button.");
    }//GEN-LAST:event_contentOptionActionPerformed

    private void sendReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendReviewActionPerformed
        String selectedContent = (String) contentOption.getSelectedItem();
        
        generated.grpc.smarttutor.RequestContent request = generated.grpc.smarttutor.RequestContent.newBuilder()
            .setContent(selectedContent)
            .build();
        
        StringBuilder tipsBuilder = new StringBuilder();

        stub.reviewContent(request, new io.grpc.stub.StreamObserver<generated.grpc.smarttutor.ContentReply>() {
        
        @Override
        public void onNext(generated.grpc.smarttutor.ContentReply value) {
            tipsBuilder.append("- ").append(value.getReply()).append("\n");
        }

        @Override
        public void onError(Throwable t) {
            reviewResults.setText("Error: " + t.getMessage());
        }

        @Override
        public void onCompleted() {
            reviewResults.setText(tipsBuilder.toString());
        }
    });
    }//GEN-LAST:event_sendReviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReviewContentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReviewContentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReviewContentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReviewContentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReviewContentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> contentOption;
    private javax.swing.JButton exitReview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea reviewResults;
    private javax.swing.JButton sendReview;
    // End of variables declaration//GEN-END:variables
}
